version: '3'

services:
    proxy:
        build: .
        ports:
            - "127.0.0.1:13194:13194"
            #- "127.0.0.1:13194:13194/udp"
        # UDP did not work, probably because the source port changes all the time
        #command: -v UDP4-RECVFROM:13194,fork UDP4-SENDTO:172.17.0.1:1194
        command: TCP-LISTEN:13194,fork TCP:172.17.0.1:1194
        restart: always

    openvpn:
        # kylemanna/openvpn:2.3
        image: kylemanna/openvpn@sha256:87380e5184b10175ea1c0c96905ef3cfe0c60606a759af016c7dcce7fb0e837a
        volumes:
            - .:/local
            - ./config:/etc/openvpn
        network_mode: host
        cap_add:
            - NET_ADMIN
        environment:
            dest: docker-for-mac.ovpn
            DEBUG: '1'
            DOCKER_NETWORK: 172.16.0.0
            DOCKER_NETMASK: 255.240.0.0
        command: /local/helpers/run.sh
        restart: always

