version: '2'

services:

    proxy:
        build: .
        ports:
            - "127.0.0.1:13194:13194"
            #- "127.0.0.1:13194:13194/udp"
        # UDP did not work, probably because the source port changes all the time
        #command: -v UDP4-RECVFROM:13194,fork UDP4-SENDTO:172.17.0.1:1194
        command: TCP-LISTEN:13194,fork TCP:172.17.0.1:1194
        restart: always

    openvpn:
        # kylemanna/openvpn:2.3
        image: f0a0813c5240026ec823d5aab4393f4674cac553fe1f2a7004e8b3dc4bf1ad01
        volumes:
            - .:/local
            - ./config:/etc/openvpn
        network_mode: host
        cap_add:
            - NET_ADMIN
        environment:
            dest: docker-for-mac.ovpn
            DEBUG: '1'
        command: /local/helpers/run.sh
        restart: always

